title: "Hyunwoong Go"
github_username: gusdnd852
github_repo: "blog"
url: "https://gusdnd852.github.io"
baseurl: "/blog" 

email: "gusdnd852@naver.com"
facebook_username: "gusdnd852"
youtube_username: "UCb7DJAuj1LulbY8WEr2EDUw"
disqus-shortname: gusdnd852
use_math: true
show_description: true
show_image: true
show_tags: true
google_analytics:

include:
  - _pages

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

minima:
    date_format: "%Y-%m-%d"

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
